<?php
/**
 * CardGatewayAgreementTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * Contact: open.source@driveoscar.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Reepay;

use PHPUnit\Framework\TestCase;

/**
 * CardGatewayAgreementTest Class Doc Comment
 *
 * @category    Class
 * @description Card gateway agreement details in case of card gateway
 * @package     Reepay
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CardGatewayAgreementTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CardGatewayAgreement"
     */
    public function testCardGatewayAgreement()
    {
    }

    /**
     * Test attribute "currencies"
     */
    public function testPropertyCurrencies()
    {
    }

    /**
     * Test attribute "surcharge"
     */
    public function testPropertySurcharge()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "provider"
     */
    public function testPropertyProvider()
    {
    }

    /**
     * Test attribute "card_types"
     */
    public function testPropertyCardTypes()
    {
    }

    /**
     * Test attribute "payment_types"
     */
    public function testPropertyPaymentTypes()
    {
    }

    /**
     * Test attribute "provider_settings"
     */
    public function testPropertyProviderSettings()
    {
    }

    /**
     * Test attribute "fee_configuration"
     */
    public function testPropertyFeeConfiguration()
    {
    }

    /**
     * Test attribute "threed_secure"
     */
    public function testPropertyThreedSecure()
    {
    }

    /**
     * Test attribute "threed_secure_recurring"
     */
    public function testPropertyThreedSecureRecurring()
    {
    }

    /**
     * Test attribute "secured_by_nets"
     */
    public function testPropertySecuredByNets()
    {
    }

    /**
     * Test attribute "secured_by_nets_recurring"
     */
    public function testPropertySecuredByNetsRecurring()
    {
    }

    /**
     * Test attribute "default_require_sca"
     */
    public function testPropertyDefaultRequireSca()
    {
    }

    /**
     * Test attribute "disallow_threed_secure_attempted"
     */
    public function testPropertyDisallowThreedSecureAttempted()
    {
    }

    /**
     * Test attribute "payout"
     */
    public function testPropertyPayout()
    {
    }

    /**
     * Test attribute "vts_configuration"
     */
    public function testPropertyVtsConfiguration()
    {
    }

    /**
     * Test attribute "scof_configuration"
     */
    public function testPropertyScofConfiguration()
    {
    }

    /**
     * Test attribute "gw_ref"
     */
    public function testPropertyGwRef()
    {
    }
}
