<?php
/**
 * ConfigurationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay Checkout API
 *
 * Reepay Checkout REST API
 *
 * OpenAPI spec version: 1
 * Contact: open.source@driveoscar.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Reepay;

use PHPUnit\Framework\TestCase;

/**
 * ConfigurationTest Class Doc Comment
 *
 * @category    Class
 * @description Configuration
 * @package     Reepay
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConfigurationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Configuration"
     */
    public function testConfiguration()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "logo"
     */
    public function testPropertyLogo()
    {
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "style_config"
     */
    public function testPropertyStyleConfig()
    {
    }

    /**
     * Test attribute "handle"
     */
    public function testPropertyHandle()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "payment_methods"
     */
    public function testPropertyPaymentMethods()
    {
    }

    /**
     * Test attribute "co_branded_card_selection"
     */
    public function testPropertyCoBrandedCardSelection()
    {
    }

    /**
     * Test attribute "co_branded_visa_dankort_preference"
     */
    public function testPropertyCoBrandedVisaDankortPreference()
    {
    }

    /**
     * Test attribute "amount_formatting"
     */
    public function testPropertyAmountFormatting()
    {
    }

    /**
     * Test attribute "payment_type_priority"
     */
    public function testPropertyPaymentTypePriority()
    {
    }

    /**
     * Test attribute "show_test_hints"
     */
    public function testPropertyShowTestHints()
    {
    }

    /**
     * Test attribute "show_subscription_details_expanded"
     */
    public function testPropertyShowSubscriptionDetailsExpanded()
    {
    }
}
