<?php
/**
 * CreateCustomerInvoiceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateCustomerInvoiceTest Class Doc Comment
 *
 * @category    Class */
// * @description CreateCustomerInvoice
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateCustomerInvoiceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CreateCustomerInvoice"
     */
    public function testCreateCustomerInvoice()
    {

    }

    /**
     * Test attribute "handle"
     */
    public function testPropertyHandle()
    {

    }

    /**
     * Test attribute "settle"
     */
    public function testPropertySettle()
    {

    }

    /**
     * Test attribute "order_lines"
     */
    public function testPropertyOrderLines()
    {

    }

    /**
     * Test attribute "manual_transfer"
     */
    public function testPropertyManualTransfer()
    {

    }

}
