<?php
/**
 * CreateSubscriptionAddOnTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateSubscriptionAddOnTest Class Doc Comment
 *
 * @category    Class */
// * @description CreateSubscriptionAddOn
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateSubscriptionAddOnTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateSubscriptionAddOn"
     */
    public function testCreateSubscriptionAddOn()
    {
    }

    /**
     * Test attribute "handle"
     */
    public function testPropertyHandle()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "add_on"
     */
    public function testPropertyAddOn()
    {
    }

    /**
     * Test attribute "fixed_amount"
     */
    public function testPropertyFixedAmount()
    {
    }

    /**
     * Test attribute "amount_incl_vat"
     */
    public function testPropertyAmountInclVat()
    {
    }
}
