<?php
/**
 * CreateSubscriptionSessionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay Checkout API
 *
 * Reepay Checkout REST API
 *
 * OpenAPI spec version: 1
 * Contact: open.source@driveoscar.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Reepay;

use PHPUnit\Framework\TestCase;

/**
 * CreateSubscriptionSessionTest Class Doc Comment
 *
 * @category    Class
 * @description CreateSubscriptionSession
 * @package     Reepay
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateSubscriptionSessionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateSubscriptionSession"
     */
    public function testCreateSubscriptionSession()
    {
    }

    /**
     * Test attribute "configuration"
     */
    public function testPropertyConfiguration()
    {
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "ttl"
     */
    public function testPropertyTtl()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "subscription"
     */
    public function testPropertySubscription()
    {
    }

    /**
     * Test attribute "accept_url"
     */
    public function testPropertyAcceptUrl()
    {
    }

    /**
     * Test attribute "cancel_url"
     */
    public function testPropertyCancelUrl()
    {
    }

    /**
     * Test attribute "payment_methods"
     */
    public function testPropertyPaymentMethods()
    {
    }

    /**
     * Test attribute "card_on_file"
     */
    public function testPropertyCardOnFile()
    {
    }

    /**
     * Test attribute "card_on_file_require_cvv"
     */
    public function testPropertyCardOnFileRequireCvv()
    {
    }

    /**
     * Test attribute "card_on_file_require_exp_date"
     */
    public function testPropertyCardOnFileRequireExpDate()
    {
    }

    /**
     * Test attribute "button_text"
     */
    public function testPropertyButtonText()
    {
    }

    /**
     * Test attribute "recurring_average_amount"
     */
    public function testPropertyRecurringAverageAmount()
    {
    }

    /**
     * Test attribute "sca_data"
     */
    public function testPropertyScaData()
    {
    }

    /**
     * Test attribute "session_data"
     */
    public function testPropertySessionData()
    {
    }

    /**
     * Test attribute "payment_method_reference"
     */
    public function testPropertyPaymentMethodReference()
    {
    }

    /**
     * Test attribute "account_funding"
     */
    public function testPropertyAccountFunding()
    {
    }

    /**
     * Test attribute "account_funding_information"
     */
    public function testPropertyAccountFundingInformation()
    {
    }

    /**
     * Test attribute "agreement_filter"
     */
    public function testPropertyAgreementFilter()
    {
    }

    /**
     * Test attribute "offline_agreement_filter"
     */
    public function testPropertyOfflineAgreementFilter()
    {
    }

    /**
     * Test attribute "allowed_ip"
     */
    public function testPropertyAllowedIp()
    {
    }

    /**
     * Test attribute "prepare_subscription"
     */
    public function testPropertyPrepareSubscription()
    {
    }

    /**
     * Test attribute "show_terms"
     */
    public function testPropertyShowTerms()
    {
    }

    /**
     * Test attribute "show_subscription_details"
     */
    public function testPropertyShowSubscriptionDetails()
    {
    }
}
