<?php
/**
 * InlineResponse20016CardTransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse20016CardTransactionTest Class Doc Comment
 *
 * @category    Class */
// * @description InlineResponse20016CardTransaction
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20016CardTransactionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "InlineResponse20016CardTransaction"
     */
    public function testInlineResponse20016CardTransaction()
    {

    }

    /**
     * Test attribute "card"
     */
    public function testPropertyCard()
    {

    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {

    }

    /**
     * Test attribute "fingerprint"
     */
    public function testPropertyFingerprint()
    {

    }

    /**
     * Test attribute "ref_transaction"
     */
    public function testPropertyRefTransaction()
    {

    }

    /**
     * Test attribute "gw_id"
     */
    public function testPropertyGwId()
    {

    }

    /**
     * Test attribute "last_failed"
     */
    public function testPropertyLastFailed()
    {

    }

    /**
     * Test attribute "first_failed"
     */
    public function testPropertyFirstFailed()
    {

    }

    /**
     * Test attribute "error_state"
     */
    public function testPropertyErrorState()
    {

    }

    /**
     * Test attribute "card_type"
     */
    public function testPropertyCardType()
    {

    }

    /**
     * Test attribute "exp_date"
     */
    public function testPropertyExpDate()
    {

    }

    /**
     * Test attribute "masked_card"
     */
    public function testPropertyMaskedCard()
    {

    }

}
