<?php
/**
 * InvoiceCreditNoteTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * Contact: open.source@driveoscar.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Reepay;

use PHPUnit\Framework\TestCase;

/**
 * InvoiceCreditNoteTest Class Doc Comment
 *
 * @category    Class
 * @description Invoice credit notes
 * @package     Reepay
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvoiceCreditNoteTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InvoiceCreditNote"
     */
    public function testInvoiceCreditNote()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "invoice"
     */
    public function testPropertyInvoice()
    {
    }

    /**
     * Test attribute "transaction"
     */
    public function testPropertyTransaction()
    {
    }

    /**
     * Test attribute "credit"
     */
    public function testPropertyCredit()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {
    }

    /**
     * Test attribute "subscription"
     */
    public function testPropertySubscription()
    {
    }

    /**
     * Test attribute "amount_vat"
     */
    public function testPropertyAmountVat()
    {
    }

    /**
     * Test attribute "amount_ex_vat"
     */
    public function testPropertyAmountExVat()
    {
    }

    /**
     * Test attribute "credit_note_lines"
     */
    public function testPropertyCreditNoteLines()
    {
    }

    /**
     * Test attribute "accounting_number"
     */
    public function testPropertyAccountingNumber()
    {
    }

    /**
     * Test attribute "debtor_id"
     */
    public function testPropertyDebtorId()
    {
    }

    /**
     * Test attribute "download_url"
     */
    public function testPropertyDownloadUrl()
    {
    }
}
