<?php
/**
 * KlarnaTransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * Contact: open.source@driveoscar.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Reepay;

use PHPUnit\Framework\TestCase;

/**
 * KlarnaTransactionTest Class Doc Comment
 *
 * @category    Class
 * @description Specifics in case of Klarna transaction
 * @package     Reepay
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class KlarnaTransactionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "KlarnaTransaction"
     */
    public function testKlarnaTransaction()
    {
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "ref_transaction"
     */
    public function testPropertyRefTransaction()
    {
    }

    /**
     * Test attribute "error_state"
     */
    public function testPropertyErrorState()
    {
    }

    /**
     * Test attribute "acquirer_message"
     */
    public function testPropertyAcquirerMessage()
    {
    }

    /**
     * Test attribute "klarna_id"
     */
    public function testPropertyKlarnaId()
    {
    }
}
