<?php
/**
 * MpoAgreementTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * Contact: open.source@driveoscar.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Reepay;

use PHPUnit\Framework\TestCase;

/**
 * MpoAgreementTest Class Doc Comment
 *
 * @category    Class
 * @description MobilePay online agreement details
 * @package     Reepay
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MpoAgreementTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MpoAgreement"
     */
    public function testMpoAgreement()
    {
    }

    /**
     * Test attribute "shop_name"
     */
    public function testPropertyShopName()
    {
    }

    /**
     * Test attribute "shop_logo_url"
     */
    public function testPropertyShopLogoUrl()
    {
    }

    /**
     * Test attribute "merchant_category_code"
     */
    public function testPropertyMerchantCategoryCode()
    {
    }

    /**
     * Test attribute "vat"
     */
    public function testPropertyVat()
    {
    }

    /**
     * Test attribute "minimum_user_age"
     */
    public function testPropertyMinimumUserAge()
    {
    }
}
