<?php
/**
 * ScaDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay Checkout API
 *
 * Reepay Checkout REST API
 *
 * OpenAPI spec version: 1
 * Contact: open.source@driveoscar.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Reepay;

use PHPUnit\Framework\TestCase;

/**
 * ScaDataTest Class Doc Comment
 *
 * @category    Class
 * @description Customer data used in strong customer authentication to reduce the need for a lengthy authentication process and ensure less fraud. The data is not stored at Reepay and only used in the process of strong customer authentication. The data is used by card issuer to determine if a frictionless authentication flow can be used.
 * @package     Reepay
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ScaDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ScaData"
     */
    public function testScaData()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "home_phone"
     */
    public function testPropertyHomePhone()
    {
    }

    /**
     * Test attribute "mobile_phone"
     */
    public function testPropertyMobilePhone()
    {
    }

    /**
     * Test attribute "work_phone"
     */
    public function testPropertyWorkPhone()
    {
    }

    /**
     * Test attribute "billing_address"
     */
    public function testPropertyBillingAddress()
    {
    }

    /**
     * Test attribute "shipping_address"
     */
    public function testPropertyShippingAddress()
    {
    }

    /**
     * Test attribute "address_match"
     */
    public function testPropertyAddressMatch()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "challenge_indicator"
     */
    public function testPropertyChallengeIndicator()
    {
    }

    /**
     * Test attribute "risk_indicator"
     */
    public function testPropertyRiskIndicator()
    {
    }

    /**
     * Test attribute "account_info"
     */
    public function testPropertyAccountInfo()
    {
    }
}
