<?php
/**
 * SepaPrefillTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay Checkout API
 *
 * Reepay Checkout REST API
 *
 * OpenAPI spec version: 1
 * Contact: open.source@driveoscar.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Reepay;

use PHPUnit\Framework\TestCase;

/**
 * SepaPrefillTest Class Doc Comment
 *
 * @category    Class
 * @description Prefill values for SEPA form
 * @package     Reepay
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SepaPrefillTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SepaPrefill"
     */
    public function testSepaPrefill()
    {
    }

    /**
     * Test attribute "verification_result"
     */
    public function testPropertyVerificationResult()
    {
    }

    /**
     * Test attribute "sepa_debtor_name"
     */
    public function testPropertySepaDebtorName()
    {
    }

    /**
     * Test attribute "sepa_debtor_address"
     */
    public function testPropertySepaDebtorAddress()
    {
    }

    /**
     * Test attribute "sepa_debtor_postal_code"
     */
    public function testPropertySepaDebtorPostalCode()
    {
    }

    /**
     * Test attribute "sepa_debtor_city"
     */
    public function testPropertySepaDebtorCity()
    {
    }

    /**
     * Test attribute "sepa_debtor_country"
     */
    public function testPropertySepaDebtorCountry()
    {
    }

    /**
     * Test attribute "sepa_debtor_iban"
     */
    public function testPropertySepaDebtorIban()
    {
    }
}
