<?php
/**
 * SubscriptionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * Contact: open.source@driveoscar.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Reepay;

use PHPUnit\Framework\TestCase;

/**
 * SubscriptionTest Class Doc Comment
 *
 * @category    Class
 * @description Subscription
 * @package     Reepay
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Subscription"
     */
    public function testSubscription()
    {
    }

    /**
     * Test attribute "handle"
     */
    public function testPropertyHandle()
    {
    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {
    }

    /**
     * Test attribute "plan"
     */
    public function testPropertyPlan()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "test"
     */
    public function testPropertyTest()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "expires"
     */
    public function testPropertyExpires()
    {
    }

    /**
     * Test attribute "reactivated"
     */
    public function testPropertyReactivated()
    {
    }

    /**
     * Test attribute "timezone"
     */
    public function testPropertyTimezone()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "activated"
     */
    public function testPropertyActivated()
    {
    }

    /**
     * Test attribute "renewing"
     */
    public function testPropertyRenewing()
    {
    }

    /**
     * Test attribute "coupons"
     */
    public function testPropertyCoupons()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "plan_version"
     */
    public function testPropertyPlanVersion()
    {
    }

    /**
     * Test attribute "amount_incl_vat"
     */
    public function testPropertyAmountInclVat()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "grace_duration"
     */
    public function testPropertyGraceDuration()
    {
    }

    /**
     * Test attribute "current_period_start"
     */
    public function testPropertyCurrentPeriodStart()
    {
    }

    /**
     * Test attribute "next_period_start"
     */
    public function testPropertyNextPeriodStart()
    {
    }

    /**
     * Test attribute "first_period_start"
     */
    public function testPropertyFirstPeriodStart()
    {
    }

    /**
     * Test attribute "last_period_start"
     */
    public function testPropertyLastPeriodStart()
    {
    }

    /**
     * Test attribute "trial_start"
     */
    public function testPropertyTrialStart()
    {
    }

    /**
     * Test attribute "trial_end"
     */
    public function testPropertyTrialEnd()
    {
    }

    /**
     * Test attribute "is_cancelled"
     */
    public function testPropertyIsCancelled()
    {
    }

    /**
     * Test attribute "in_trial"
     */
    public function testPropertyInTrial()
    {
    }

    /**
     * Test attribute "has_started"
     */
    public function testPropertyHasStarted()
    {
    }

    /**
     * Test attribute "renewal_count"
     */
    public function testPropertyRenewalCount()
    {
    }

    /**
     * Test attribute "cancelled_date"
     */
    public function testPropertyCancelledDate()
    {
    }

    /**
     * Test attribute "expired_date"
     */
    public function testPropertyExpiredDate()
    {
    }

    /**
     * Test attribute "expire_reason"
     */
    public function testPropertyExpireReason()
    {
    }

    /**
     * Test attribute "on_hold_date"
     */
    public function testPropertyOnHoldDate()
    {
    }

    /**
     * Test attribute "on_hold_reason"
     */
    public function testPropertyOnHoldReason()
    {
    }

    /**
     * Test attribute "payment_method_added"
     */
    public function testPropertyPaymentMethodAdded()
    {
    }

    /**
     * Test attribute "scheduled_plan_change"
     */
    public function testPropertyScheduledPlanChange()
    {
    }

    /**
     * Test attribute "reminder_email_sent"
     */
    public function testPropertyReminderEmailSent()
    {
    }

    /**
     * Test attribute "failed_invoices"
     */
    public function testPropertyFailedInvoices()
    {
    }

    /**
     * Test attribute "failed_amount"
     */
    public function testPropertyFailedAmount()
    {
    }

    /**
     * Test attribute "cancelled_invoices"
     */
    public function testPropertyCancelledInvoices()
    {
    }

    /**
     * Test attribute "cancelled_amount"
     */
    public function testPropertyCancelledAmount()
    {
    }

    /**
     * Test attribute "pending_invoices"
     */
    public function testPropertyPendingInvoices()
    {
    }

    /**
     * Test attribute "pending_amount"
     */
    public function testPropertyPendingAmount()
    {
    }

    /**
     * Test attribute "dunning_invoices"
     */
    public function testPropertyDunningInvoices()
    {
    }

    /**
     * Test attribute "dunning_amount"
     */
    public function testPropertyDunningAmount()
    {
    }

    /**
     * Test attribute "settled_invoices"
     */
    public function testPropertySettledInvoices()
    {
    }

    /**
     * Test attribute "settled_amount"
     */
    public function testPropertySettledAmount()
    {
    }

    /**
     * Test attribute "refunded_amount"
     */
    public function testPropertyRefundedAmount()
    {
    }

    /**
     * Test attribute "pending_additional_costs"
     */
    public function testPropertyPendingAdditionalCosts()
    {
    }

    /**
     * Test attribute "pending_additional_cost_amount"
     */
    public function testPropertyPendingAdditionalCostAmount()
    {
    }

    /**
     * Test attribute "transferred_additional_costs"
     */
    public function testPropertyTransferredAdditionalCosts()
    {
    }

    /**
     * Test attribute "transferred_additional_cost_amount"
     */
    public function testPropertyTransferredAdditionalCostAmount()
    {
    }

    /**
     * Test attribute "pending_credits"
     */
    public function testPropertyPendingCredits()
    {
    }

    /**
     * Test attribute "pending_credit_amount"
     */
    public function testPropertyPendingCreditAmount()
    {
    }

    /**
     * Test attribute "transferred_credits"
     */
    public function testPropertyTransferredCredits()
    {
    }

    /**
     * Test attribute "transferred_credit_amount"
     */
    public function testPropertyTransferredCreditAmount()
    {
    }

    /**
     * Test attribute "hosted_page_links"
     */
    public function testPropertyHostedPageLinks()
    {
    }

    /**
     * Test attribute "subscription_discounts"
     */
    public function testPropertySubscriptionDiscounts()
    {
    }

    /**
     * Test attribute "pending_change"
     */
    public function testPropertyPendingChange()
    {
    }

    /**
     * Test attribute "subscription_changes"
     */
    public function testPropertySubscriptionChanges()
    {
    }

    /**
     * Test attribute "subscription_add_ons"
     */
    public function testPropertySubscriptionAddOns()
    {
    }

    /**
     * Test attribute "active_payment_methods"
     */
    public function testPropertyActivePaymentMethods()
    {
    }
}
