<?php
/**
 * TransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * Contact: open.source@driveoscar.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Reepay;

use PHPUnit\Framework\TestCase;

/**
 * TransactionTest Class Doc Comment
 *
 * @category    Class
 * @description Invoice transactions
 * @package     Reepay
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TransactionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Transaction"
     */
    public function testTransaction()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "invoice"
     */
    public function testPropertyInvoice()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "settled"
     */
    public function testPropertySettled()
    {
    }

    /**
     * Test attribute "authorized"
     */
    public function testPropertyAuthorized()
    {
    }

    /**
     * Test attribute "failed"
     */
    public function testPropertyFailed()
    {
    }

    /**
     * Test attribute "refunded"
     */
    public function testPropertyRefunded()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "payment_type"
     */
    public function testPropertyPaymentType()
    {
    }

    /**
     * Test attribute "payment_method"
     */
    public function testPropertyPaymentMethod()
    {
    }

    /**
     * Test attribute "card_transaction"
     */
    public function testPropertyCardTransaction()
    {
    }

    /**
     * Test attribute "mpo_transaction"
     */
    public function testPropertyMpoTransaction()
    {
    }

    /**
     * Test attribute "vipps_transaction"
     */
    public function testPropertyVippsTransaction()
    {
    }

    /**
     * Test attribute "applepay_transaction"
     */
    public function testPropertyApplepayTransaction()
    {
    }

    /**
     * Test attribute "googlepay_transaction"
     */
    public function testPropertyGooglepayTransaction()
    {
    }

    /**
     * Test attribute "manual_transaction"
     */
    public function testPropertyManualTransaction()
    {
    }

    /**
     * Test attribute "viabill_transaction"
     */
    public function testPropertyViabillTransaction()
    {
    }

    /**
     * Test attribute "anyday_transaction"
     */
    public function testPropertyAnydayTransaction()
    {
    }

    /**
     * Test attribute "santander_transaction"
     */
    public function testPropertySantanderTransaction()
    {
    }

    /**
     * Test attribute "resurs_transaction"
     */
    public function testPropertyResursTransaction()
    {
    }

    /**
     * Test attribute "klarna_transaction"
     */
    public function testPropertyKlarnaTransaction()
    {
    }

    /**
     * Test attribute "swish_transaction"
     */
    public function testPropertySwishTransaction()
    {
    }

    /**
     * Test attribute "paypal_transaction"
     */
    public function testPropertyPaypalTransaction()
    {
    }

    /**
     * Test attribute "bancontact_transaction"
     */
    public function testPropertyBancontactTransaction()
    {
    }

    /**
     * Test attribute "blik_transaction"
     */
    public function testPropertyBlikTransaction()
    {
    }

    /**
     * Test attribute "ideal_transaction"
     */
    public function testPropertyIdealTransaction()
    {
    }

    /**
     * Test attribute "p24_transaction"
     */
    public function testPropertyP24Transaction()
    {
    }

    /**
     * Test attribute "trustly_transaction"
     */
    public function testPropertyTrustlyTransaction()
    {
    }

    /**
     * Test attribute "eps_transaction"
     */
    public function testPropertyEpsTransaction()
    {
    }

    /**
     * Test attribute "estonia_banks_transaction"
     */
    public function testPropertyEstoniaBanksTransaction()
    {
    }

    /**
     * Test attribute "latvia_banks_transaction"
     */
    public function testPropertyLatviaBanksTransaction()
    {
    }

    /**
     * Test attribute "lithuania_banks_transaction"
     */
    public function testPropertyLithuaniaBanksTransaction()
    {
    }

    /**
     * Test attribute "mbway_transaction"
     */
    public function testPropertyMbwayTransaction()
    {
    }

    /**
     * Test attribute "multibanco_transaction"
     */
    public function testPropertyMultibancoTransaction()
    {
    }

    /**
     * Test attribute "mybank_transaction"
     */
    public function testPropertyMybankTransaction()
    {
    }

    /**
     * Test attribute "payconiq_transaction"
     */
    public function testPropertyPayconiqTransaction()
    {
    }

    /**
     * Test attribute "paysafecard_transaction"
     */
    public function testPropertyPaysafecardTransaction()
    {
    }

    /**
     * Test attribute "paysera_transaction"
     */
    public function testPropertyPayseraTransaction()
    {
    }

    /**
     * Test attribute "postfinance_transaction"
     */
    public function testPropertyPostfinanceTransaction()
    {
    }

    /**
     * Test attribute "satispay_transaction"
     */
    public function testPropertySatispayTransaction()
    {
    }

    /**
     * Test attribute "wechatpay_transaction"
     */
    public function testPropertyWechatpayTransaction()
    {
    }

    /**
     * Test attribute "mps_transaction"
     */
    public function testPropertyMpsTransaction()
    {
    }

    /**
     * Test attribute "vipps_recurring_transaction"
     */
    public function testPropertyVippsRecurringTransaction()
    {
    }

    /**
     * Test attribute "payment_context"
     */
    public function testPropertyPaymentContext()
    {
    }
}
