<?php
/**
 * AdditionalCostApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * Contact: open.source@driveoscar.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Reepay;

use Reepay\Configuration;
use Reepay\ApiException;
use Reepay\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AdditionalCostApiTest Class Doc Comment
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AdditionalCostApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cancelAdditionalCost
     *
     * Cancel pending additional cost.
     *
     */
    public function testCancelAdditionalCost()
    {
    }

    /**
     * Test case for createAdditionalCostJson
     *
     * Create additional cost.
     *
     */
    public function testCreateAdditionalCostJson()
    {
    }

    /**
     * Test case for getAdditionalCost
     *
     * Get additional cost.
     *
     */
    public function testGetAdditionalCost()
    {
    }

    /**
     * Test case for getAdditionalCosts
     *
     * Get additional costs for subscription.
     *
     */
    public function testGetAdditionalCosts()
    {
    }
}
