<?php
/**
 * CustomerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CustomerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for activatePaymentMethod
     *
     * Activate payment method.
     *
     */
    public function testActivatePaymentMethod()
    {

    }

    /**
     * Test case for addCardJson
     *
     * Add card payment method.
     *
     */
    public function testAddCardJson()
    {

    }

    /**
     * Test case for createCustomerInvoice
     *
     * Create invoice for customer.
     *
     */
    public function testCreateCustomerInvoice()
    {

    }

    /**
     * Test case for createCustomerJson
     *
     * Create customer.
     *
     */
    public function testCreateCustomerJson()
    {

    }

    /**
     * Test case for createCustomerNoteJson
     *
     * Create customer note.
     *
     */
    public function testCreateCustomerNoteJson()
    {

    }

    /**
     * Test case for deleteCustomer
     *
     * Delete customer.
     *
     */
    public function testDeleteCustomer()
    {

    }

    /**
     * Test case for getCard
     *
     * Get card.
     *
     */
    public function testGetCard()
    {

    }

    /**
     * Test case for getCardDetails
     *
     * Get gateway card details.
     *
     */
    public function testGetCardDetails()
    {

    }

    /**
     * Test case for getCustomer
     *
     * Get customer.
     *
     */
    public function testGetCustomer()
    {

    }

    /**
     * Test case for getCustomerNotes
     *
     * Get customer notes.
     *
     */
    public function testGetCustomerNotes()
    {

    }

    /**
     * Test case for getCustomerPaymentMethods
     *
     * Get payment methods.
     *
     */
    public function testGetCustomerPaymentMethods()
    {

    }

    /**
     * Test case for getCustomers
     *
     * Get list of customers.
     *
     */
    public function testGetCustomers()
    {

    }

    /**
     * Test case for importCardJson
     *
     * Import card payment method.
     *
     */
    public function testImportCardJson()
    {

    }

    /**
     * Test case for inactivatePaymentMethod
     *
     * Inactivate payment method.
     *
     */
    public function testInactivatePaymentMethod()
    {

    }

    /**
     * Test case for reactivateCard
     *
     * Reactivate failed card.
     *
     */
    public function testReactivateCard()
    {

    }

    /**
     * Test case for updateCustomerJson
     *
     * Update customer.
     *
     */
    public function testUpdateCustomerJson()
    {

    }

}
