<?php
/**
 * PaymentMethodApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * Contact: open.source@driveoscar.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Reepay;

use Reepay\Configuration;
use Reepay\ApiException;
use Reepay\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PaymentMethodApiTest Class Doc Comment
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PaymentMethodApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for activatePaymentMethodV2
     *
     * Activate payment method.
     *
     */
    public function testActivatePaymentMethodV2()
    {
    }

    /**
     * Test case for addPaymentMethodV2
     *
     * Add payment method.
     *
     */
    public function testAddPaymentMethodV2()
    {
    }

    /**
     * Test case for cardVerification
     *
     * Verify card validity.
     *
     */
    public function testCardVerification()
    {
    }

    /**
     * Test case for copyCardPaymentMethodV2
     *
     * Copy card to customer.
     *
     */
    public function testCopyCardPaymentMethodV2()
    {
    }

    /**
     * Test case for deletePaymentMethodV2
     *
     * Delete payment method.
     *
     */
    public function testDeletePaymentMethodV2()
    {
    }

    /**
     * Test case for enrollCardPaymentMethodV2
     *
     * Enroll card to EMV Token.
     *
     */
    public function testEnrollCardPaymentMethodV2()
    {
    }

    /**
     * Test case for getCardTokenDetails
     *
     * Get card token details.
     *
     */
    public function testGetCardTokenDetails()
    {
    }

    /**
     * Test case for getPaymentMethodDetailsV2
     *
     * Get payment method details.
     *
     */
    public function testGetPaymentMethodDetailsV2()
    {
    }

    /**
     * Test case for getPaymentMethodV2
     *
     * Get payment method.
     *
     */
    public function testGetPaymentMethodV2()
    {
    }

    /**
     * Test case for importMpsPaymentMethod
     *
     * Import MobilePay Subscription payment method.
     *
     */
    public function testImportMpsPaymentMethod()
    {
    }

    /**
     * Test case for importVippsRecurringPaymentMethod
     *
     * Import Vipps Recurring payment method.
     *
     */
    public function testImportVippsRecurringPaymentMethod()
    {
    }

    /**
     * Test case for inactivatePaymentMethodV2
     *
     * Inactivate payment method.
     *
     */
    public function testInactivatePaymentMethodV2()
    {
    }

    /**
     * Test case for moveCardPaymentMethodV2
     *
     * Move card to other agreement.
     *
     */
    public function testMoveCardPaymentMethodV2()
    {
    }

    /**
     * Test case for reactivateCardV2
     *
     * Reactivate failed card.
     *
     */
    public function testReactivateCardV2()
    {
    }
}
